# Generated by Django 6.1 on 2026-09-15 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0002_transaction_transfer_account_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="account_type",
            field=models.CharField(
                choices=[
                    ("CASH", "Efectivo"),
                    ("BANK", "Cuenta bancaria"),
                    ("NEQUI", "Nequi"),
                    ("DIGITAL", "Billetera digital"),
                    ("OTHER", "Otro"),
                ],
                db_index=True,
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="account",
            name="is_active",
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name="account",
            name="name",
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="category",
            name="is_active",
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="category",
            name="type",
            field=models.CharField(
                choices=[("INCOME", "Ingreso"), ("EXPENSE", "Gasto")],
                db_index=True,
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="debt",
            name="due_date",
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="debt",
            name="paid_amount",
            field=models.DecimalField(
                db_index=True, decimal_places=2, default=0, max_digits=12
            ),
        ),
        migrations.AlterField(
            model_name="debt",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pendiente"),
                    ("PARTIAL", "Pago parcial"),
                    ("PAID", "Pagada"),
                ],
                db_index=True,
                default="PENDING",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="reservedfund",
            name="deadline",
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="reservedfund",
            name="is_completed",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="savingsgoal",
            name="current_amount",
            field=models.DecimalField(
                db_index=True, decimal_places=2, default=0, max_digits=12
            ),
        ),
        migrations.AlterField(
            model_name="savingsgoal",
            name="deadline",
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="savingsgoal",
            name="is_completed",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="date",
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="type",
            field=models.CharField(
                choices=[
                    ("INCOME", "Ingreso"),
                    ("EXPENSE", "Gasto"),
                    ("TRANSFER", "Transferencia"),
                ],
                db_index=True,
                max_length=10,
            ),
        ),
    ]
