# Generated by Django 6.1 on 2026-08-10 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bot", "0001_initial"),
        ("finance", "0002_transaction_transfer_account_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="pending_transfer_account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pending_transfer_conversations",
                to="finance.account",
            ),
        ),
    ]
