# Generated by Django 6.1 on 2026-08-18 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_conversation_pending_transfer_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='state',
            field=models.CharField(choices=[('IDLE', 'Inactiva'), ('WAITING_FOR_ACCOUNT', 'Esperando cuenta'), ('WAITING_FOR_TRANSFER_DESTINATION', 'Esperando cuenta destino'), ('WAITING_FOR_CATEGORY', 'Esperando categoría'), ('WAITING_FOR_AMOUNT', 'Esperando monto'), ('CONFIRMING', 'Esperando confirmación')], default='IDLE', max_length=40),
        ),
    ]