# Generated by Django 6.1 on 2026-09-15 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bot", "0003_alter_conversation_state"),
    ]

    operations = [
        migrations.AlterField(
            model_name="conversation",
            name="pending_type",
            field=models.CharField(blank=True, db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name="conversation",
            name="state",
            field=models.CharField(
                choices=[
                    ("IDLE", "Inactiva"),
                    ("WAITING_FOR_ACCOUNT", "Esperando cuenta"),
                    ("WAITING_FOR_TRANSFER_DESTINATION", "Esperando cuenta destino"),
                    ("WAITING_FOR_CATEGORY", "Esperando categoría"),
                    ("WAITING_FOR_AMOUNT", "Esperando monto"),
                    ("CONFIRMING", "Esperando confirmación"),
                ],
                db_index=True,
                default="IDLE",
                max_length=40,
            ),
        ),
    ]
