# Tipos de transacción
TRANSACTION_TYPE_EXPENSE = "EXPENSE"
TRANSACTION_TYPE_INCOME = "INCOME"
TRANSACTION_TYPE_TRANSFER = "TRANSFER"

# Estados de conversación
STATE_IDLE = "IDLE"
STATE_WAITING_FOR_ACCOUNT = "WAITING_FOR_ACCOUNT"
STATE_WAITING_FOR_TRANSFER_DESTINATION = "WAITING_FOR_TRANSFER_DESTINATION"
STATE_WAITING_FOR_CATEGORY = "WAITING_FOR_CATEGORY"
STATE_WAITING_FOR_AMOUNT = "WAITING_FOR_AMOUNT"
STATE_CONFIRMING = "CONFIRMING"

# Períodos
PERIOD_TODAY = "TODAY"
PERIOD_YESTERDAY = "YESTERDAY"
PERIOD_WEEK = "WEEK"
PERIOD_MONTH = "MONTH"
PERIOD_LAST_MONTH = "LAST_MONTH"

# Tipos de consulta
QUERY_TYPE_BALANCE = "BALANCE"
QUERY_TYPE_MONTH_SUMMARY = "MONTH_SUMMARY"
QUERY_TYPE_EXPENSE_TOTAL = "EXPENSE_TOTAL"
QUERY_TYPE_INCOME_TOTAL = "INCOME_TOTAL"
QUERY_TYPE_TOP_EXPENSE = "TOP_EXPENSE"
QUERY_TYPE_EXPENSES_BREAKDOWN = "EXPENSES_BREAKDOWN"
QUERY_TYPE_INCOME_BREAKDOWN = "INCOME_BREAKDOWN"
QUERY_TYPE_CATEGORY_TOTAL = "CATEGORY_TOTAL"

# Confirmación
CONFIRMATION_YES = ["si", "sí", "s", "confirmar", "confirmo", "dale", "ok"]
CONFIRMATION_NO = ["no", "n", "cancelar", "cancela"]

# Nombres de campos de pending
PENDING_TYPE = "pending_type"
PENDING_AMOUNT = "pending_amount"
PENDING_CATEGORY = "pending_category"
PENDING_ACCOUNT = "pending_account"
PENDING_TRANSFER_ACCOUNT = "pending_transfer_account"
PENDING_DESCRIPTION = "pending_description"

# Tipos de consulta financiera extendida
QUERY_TYPE_RESERVED_FUNDS = "RESERVED_FUNDS"
QUERY_TYPE_SAVINGS_GOALS = "SAVINGS_GOALS"
QUERY_TYPE_DEBTS = "DEBTS"
QUERY_TYPE_BUDGETS = "BUDGETS"
QUERY_TYPE_DELETE_TRANSACTION = "DELETE_TRANSACTION"

# Confirmación para eliminar
CONFIRMATION_DELETE_YES = ["si", "sí", "s", "confirmar", "confirmo", "dale", "ok", "eliminar", "borrar"]
CONFIRMATION_DELETE_NO = ["no", "n", "cancelar", "cancela", "guardar"]

# Estados para gestión financiera
STATE_WAITING_RESERVED_FUND_NAME = "WAITING_RESERVED_FUND_NAME"
STATE_WAITING_RESERVED_FUND_AMOUNT = "WAITING_RESERVED_FUND_AMOUNT"
STATE_WAITING_RESERVED_FUND_ACCOUNT = "WAITING_RESERVED_FUND_ACCOUNT"
STATE_WAITING_SAVINGS_GOAL_TARGET = "WAITING_SAVINGS_GOAL_TARGET"
STATE_WAITING_DEBT_AMOUNT = "WAITING_DEBT_AMOUNT"
STATE_WAITING_BUDGET_LIMIT = "WAITING_BUDGET_LIMIT"
STATE_WAITING_BUDGET_CATEGORY = "WAITING_BUDGET_CATEGORY"
STATE_WAITING_BUDGET_MONTH = "WAITING_BUDGET_MONTH"
STATE_WAITING_BUDGET_YEAR = "WAITING_BUDGET_YEAR"

# Estados para eliminar transacción
STATE_WAITING_DELETE_CONFIRMATION = "WAITING_DELETE_CONFIRMATION"
STATE_WAITING_DELETE_SELECTION = "WAITING_DELETE_SELECTION"
